### ISSUE TITLE
"BNmode" argument in "utils.py" seems to mismatch with definition in "models"

### ISSUE THREAD

**Issue by kuz44ma69** [huster-wgm/VSIAD#3]
The case net != "res18ynetsyncGN", "BNmode" argument is set to "True".
(Please check below.)

https://github.com/huster-wgm/VSIAD/blob/4b387e6cb63a7f995d7235ac744daee96f3485a0/src/utils.py#L26-L33

https://github.com/huster-wgm/VSIAD/blob/4b387e6cb63a7f995d7235ac744daee96f3485a0/src/utils.py#L36

But this argument seems to need to be string like "BN" or "IN" or "GN.
(Please check below.)
https://github.com/huster-wgm/VSIAD/blob/4b387e6cb63a7f995d7235ac744daee96f3485a0/src/models/resynetsync.py#L34-L39

**Comment by huster-wgm** [comment]
As suggested, utils.py had been updated.

**Comment by kuz44ma69** [comment]
Thans a lot!
